feat: ✨ shell themes for fzf and skim
fenetikm/falcon pull request #83
Opened 2024-11-27 21:37 UTC by tkapias

Themes for [fzf](https://github.com/junegunn/fzf) and [skim](https://github.com/skim-rs/skim).

![image](https://github.com/user-attachments/assets/cef73999-4b13-4632-a535-db472b007478)

2024-11-28 04:37 UTC, fenetikm requested changes
Looks good - just a couple of things to clean up please :)

2024-11-28 04:37 UTC, fenetikm commented on fzf-skim/.bashrc
> +--pointer='>' \
probs shouldn't override this and the next line, just the colours.

2024-11-28 04:37 UTC, fenetikm commented on fzf-skim/.bashrc
> +export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
think it's better to put this into it's own file, say `fzf/fzf.sh`

2024-11-28 04:37 UTC, fenetikm commented on fzf-skim/.bashrc
> +# Falcon color themes for fzf and skim
think these comments are redundant - also put this into its own file at `skim/skim.sh`

2024-12-01 19:23 UTC, tkapias commented
I separated fzf and skim in 2 folders and remove --pointer and --marker.

2024-12-02 21:52 UTC, fenetikm commented
Thanks, appreciate it :)

2024-12-02 21:52 UTC, merged