feat: ✨ themes for bat and nb
fenetikm/falcon pull request #84
Opened 2024-11-27 22:05 UTC by tkapias

I duplicated sublime/falcon.tmTheme to use it for [bat](https://github.com/sharkdp/bat).

I put it together with a config file and instructions for [nb](https://github.com/xwmx/nb) which uses bat.

2024-11-28 05:37 UTC, fenetikm commented on bat-nb/README.md
> +## bat
can you please split this PR into having a directory for each separately? i.e. `bat/` and `nb/` ?

2024-11-28 05:37 UTC, fenetikm requested changes

2024-11-28 05:37 UTC, fenetikm commented on bat-nb/README.md
> +## bat
can you please split this PR into having a directory for each separately? i.e. bat/ and nb/ ?

2024-12-01 19:51 UTC, tkapias commented
I separated them in 2 folders.

I also left a TODO file for a tool related to nb: ACE Editor. I can delete it if it's the wrong place to keep the info.

2024-12-02 05:22 UTC, tkapias commented
Closing this as I split this PR, first in PR #88 for bat, and I will add another one for nb.

2024-12-02 05:22 UTC, closed without merging